name: build

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

env:
  LC_CTYPE: en_US.UTF-8
  LANG: en_US.UTF-8

jobs:
  macOS-5_3:
    name: Build macOS Swift (5.3)
    runs-on: macos-11.0
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.3.app/Contents/Developer
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache build
        uses: actions/cache@v2
        with:
          path: |
            ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-build-xcode-12
      - name: Build
        run: swift build -v