name: build

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

env:
  LC_CTYPE: en_US.UTF-8
  LANG: en_US.UTF-8
  PROJECT: ProgressX.xcodeproj
  SCHEME: ProgressX
  
jobs:
  build:
    runs-on: macos-10.15
    strategy:
      matrix:
        destination: 
          - 'platform=iOS Simulator,name=iPhone 11 Pro,OS=13.6'
          - 'platform=tvOS Simulator,name=Apple TV,OS=13.3'
          - 'platform=OS X,arch=x86_64'
          - 'platform=watchOS Simulator,name=Apple Watch Series 5 - 40mm,OS=6.2.1'
    
    steps:
      - uses: actions/checkout@v2
      - run: xcodebuild build -project $PROJECT -scheme $SCHEME -destination "${{ matrix.destination }}"
