name: Unit test

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

env:
  LC_CTYPE: en_US.UTF-8
  LANG: en_US.UTF-8

jobs:
  macOS-5_3:
    name: Unit test macOS Swift (5.3)
    runs-on: macos-11.0
    env: 
      DEVELOPER_DIR: /Applications/Xcode_12.3.app/Contents/Developer
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache build
        uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-test-xcode-12
      - name: Test
        run: swift test --enable-code-coverage -v 2>&1 | xcpretty