name: Unit test

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

env:
  LC_CTYPE: en_US.UTF-8
  LANG: en_US.UTF-8

jobs:
  unit-test-latest:
    name: Unit test macOS latest
    runs-on: macos-latest
    env: 
      DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache build
        uses: actions/cache@v2
        with:
          path: |
            .build
          key: ${{ runner.os }}-build-cache
      - name: Test
        run: swift test --enable-code-coverage -v 2>&1 | xcpretty
      - name: Export code coverage
        if: github.ref == 'refs/heads/develop'
        run: xcrun llvm-cov export -format="lcov" .build/x86_64-apple-macosx/debug/ProgressXPackageTests.xctest/Contents/MacOS/ProgressXPackageTests -instr-profile=.build/x86_64-apple-macosx/debug/codecov/default.profdata > .build/progressx-coverage.lcov
      - name: Upload code coverage
        if: github.ref == 'refs/heads/develop'
        uses: codecov/codecov-action@v1
        with:
          file: .build/progressx-coverage.lcov
          fail_ci_if_error: true
          verbose: true